apiVersion: v1
kind: Pod
metadata:
  name: successful-pod
  labels:
    app: intuit
  namespace: default
spec:
  containers:
    - name: main
      image: busybox:1.28
      command: [ "/bin/sh" ]
      args:
        - "-c"
        - "exit 0"
  restartPolicy: Never
