apiVersion: v1
kind: Pod
metadata:
  name: terminating-pod
  labels:
    app: intuit
  namespace: default
spec:
  terminationGracePeriodSeconds: 50000
  containers:
    - name: main
      image: busybox:1.28
      command: [ "/bin/sh" ]
      args:
      - "-c"
      - "sleep 99999"